### ISSUE TITLE
Should not use 'System' as the namespace to qualify your library

### ISSUE THREAD

**Issue by goblinfactory** [tsolarin/readline#58]
Readline should not use System namespace. This will make it not possible to use this library in any enterprise project that has any package reviewing process.

I suggest the root namespace be created called something e.g. Tonerdo or similar and a new release be created (version 3) with the new namespace.

Great library btw! nice :D

**Comment by Latency** [comment]
The default namespace is 'ReadLine'.

```CSharp
namespace ReadLine {
...
}
```

Use my latest release if you are having issues.  Tonerdo has been busy to maintain this repo and merge the PRs associated.

**Where are  you seeing 'System' namespace being used?**

Removing references to 'System' namespace is not going to happen.  Console.Read() is found within the '_System_' namespace.

Using Win32 to pinvoke and proxy the STDIN as described [here](https://stackoverflow.com/questions/9479573/how-to-interrupt-console-readline), is not necessary. 
 This API is going to remain as is since it works just fine according to feedback from our user base.

I think we have done a fairly good job recreating this API for Windows using pure managed libraries.

**Comment by goblinfactory** [comment]
re: where are you seeing `System`

<img width="456" alt="Screen Shot 2020-01-20 at 11 14 16" src="https://user-images.githubusercontent.com/1073487/72722452-42232280-3b76-11ea-99ad-22954ef7ec1a.png">

[your source file -> ReadLine.cs](https://github.com/tonerdo/readline/blob/master/src/ReadLine/ReadLine.cs)

re: `Using Win32 to pinvoke and proxy`
This issue doesn't mention that.

**Comment by goblinfactory** [comment]
re: Removing referneces to `System` namespace is not going to happen
Ah, I see the confusion. I have renamed the issue title

old title :" Should not use System namespace " 

new title : "Should not use 'System' as the namespace to qualify your library"

Re: I think we have done a fairly good job
I agree, which is why I care enough to give helpful feedback. Also why I wrote, "Great library btw! nice :D" at the bottom of the issue. 
grin!
keep it up

**Comment by Latency** [comment]
Do not use Tonerdo build or old release.

The 'System' namespace was refactored a long time ago.

 Use my forked release found on my page.  It is the latest release since I do not have admin access to merge into 'master'.

-----------------------

**This issue should be noted as resolved / closed!!!**

**Comment by goblinfactory** [comment]
just checked it out! txs looks good 👍
link here in case anyone else reads this thread later : 
https://github.com/Latency/ReadLine

cheers, 
A
